#!/usr/bin/env python3
"""Generate diagram.json and keypad.test.yaml from the firmware's own tables.

The key matrix is read from s_map in firmware/main/keypad.c and the pins from
firmware/main/board.h (with HP42S_WOKWI), so the simulation cannot drift from
the code it tests. Run it after either file changes:

    python3 sim/wokwi/gen_diagram.py
"""
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
FW = HERE.parent.parent / "firmware" / "main"


def parse_map():
    src = (FW / "keypad.c").read_text()
    body = re.search(r"s_map\[KP_ROWS\]\[KP_COLS\]\s*=\s*\{(.*?)\n\};", src, re.S).group(1)
    rows = re.findall(r"\{([^}]*)\}", body)
    return [[int(v) for v in r.split(",") if v.strip()] for r in rows]


def parse_pins():
    src = (FW / "board.h").read_text()

    def arr(name):
        body = re.search(name + r"\[\w+\]\s*=\s*\{(.*?)\};", src, re.S).group(1)
        return [int(n) for n in re.findall(r"GPIO_NUM_(\d+)", body)]

    # The #else branch is the Wokwi one.
    wokwi = re.search(r"#else(.*?)#endif", src, re.S).group(1)
    epd = {k: int(v) for k, v in re.findall(r"#define EPD_(\w+)\s+GPIO_NUM_(\d+)", wokwi)}
    for k, v in re.findall(r"#define EPD_(\w+)\s+GPIO_NUM_(\d+)", src):
        epd.setdefault(k, int(v))
    return arr("kp_col"), arr("kp_row"), epd


def parse_names():
    src = (HERE / "firmware" / "main" / "sim_main.c").read_text()
    body = re.search(r"s_names\[KEY_MAX \+ 1\]\s*=\s*\{(.*?)\};", src, re.S).group(1)
    return re.findall(r'"([^"]*)"', body)


def main():
    kmap = parse_map()
    cols, rows, epd = parse_pins()
    names = parse_names()
    assert len(kmap) == len(rows) and all(len(r) == len(cols) for r in kmap)

    parts = [
        {"type": "board-esp32-s3-devkitc-1", "id": "esp", "top": 0, "left": 0, "attrs": {}},
        {"type": "chip-ssd1680", "id": "epd", "top": -230, "left": 250, "attrs": {}},
    ]
    conns = [
        ["esp:TX", "$serialMonitor:RX", "", []],
        ["esp:RX", "$serialMonitor:TX", "", []],
        ["epd:VCC", "esp:3V3.1", "red", []],
        ["epd:GND", "esp:GND.1", "black", []],
    ]
    for pin, sig in [("CS", "CS"), ("DC", "DC"), ("RST", "RST"),
                     ("BUSY", "BUSY"), ("SCK", "SCK"), ("SDI", "MOSI")]:
        conns.append([f"epd:{pin}", f"esp:{epd[sig]}", "green", []])

    steps = [{"wait-serial": "hp42s sim ready"}]
    keys = 0
    for r, row in enumerate(kmap):
        for c, k in enumerate(row):
            if k == 0:
                continue
            keys += 1
            bid = f"k{k}"
            parts.append({
                "type": "wokwi-pushbutton", "id": bid,
                "top": 40 + r * 60, "left": 300 + c * 80,
                "attrs": {"color": "grey", "label": names[k]},
            })
            # One side to the row line, the other to the column line, as the
            # dome bridges them on the board.
            conns.append([f"{bid}:1.l", f"esp:{rows[r]}", "blue", []])
            conns.append([f"{bid}:2.r", f"esp:{cols[c]}", "orange", []])
            steps += [
                {"set-control": {"part-id": bid, "control": "pressed", "value": 1}},
                {"wait-serial": f"key {k} {names[k]}"},
                {"set-control": {"part-id": bid, "control": "pressed", "value": 0}},
                {"wait-serial": f"up {k}"},
            ]
    assert keys == 37, keys

    diagram = {"version": 1, "author": "HP-42S clone", "editor": "wokwi",
               "parts": parts, "connections": conns, "dependencies": {}}
    (HERE / "diagram.json").write_text(json.dumps(diagram, indent=2) + "\n")

    lines = ["# Generated by gen_diagram.py -- edit that, not this.",
             "name: Every key reports itself once",
             "version: 1",
             "author: HP-42S clone",
             "steps:"]
    for s in steps:
        lines.append("  - " + json.dumps(s))
    (HERE / "keypad.test.yaml").write_text("\n".join(lines) + "\n")
    print(f"{keys} keys, {len(conns)} connections, {len(steps)} scenario steps")


if __name__ == "__main__":
    main()
