M48
; DRILL file KiCad 10.0.3 date 2026-09-28T13:11:05
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-28T13:11:05+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X35.11Y-5.08
X40.89Y-5.08
T2
X58.525Y-1.8
X62.775Y-1.8
X69.185Y-1.8
X73.435Y-1.8
M30
